### ISSUE TITLE
Add "technical specifications" view with full npe2 metadata and links to Github implementations

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/napari-hub#543]
### Who its for

Plugin developers exploring each other's plugins

### Problem it solves

Plugin developers rely on the napari hub to learn more about other plugins that are being developed so that they can

### How it works

With the recent addition of npe2 support, we have access to the full "manifest" file, which specifies the functionality of each plugin.

For example, for stardist:

``` yaml
name: stardist-napari
schema_version: 0.1.0
contributions:
  commands:
  - id: stardist-napari.widget
    title: Create StarDist widget
    python_name: stardist_napari:make_dock_widget
  - id: stardist-napari.data.nuclei_2d
    title: Nuclei (2D) sample
    python_name: stardist_napari._sample_data:_test_image_nuclei_2d
  - id: stardist-napari.data.he_2d
    title: H&E Nuclei (2D RGB) sample
    python_name: stardist_napari._sample_data:_test_image_he_2d
  - id: stardist-napari.data.nuclei_3d
    title: Nuclei (3D) sample
    python_name: stardist_napari._sample_data:_test_image_nuclei_3d
  widgets:
  - command: stardist-napari.widget
    display_name: StarDist
  sample_data:
  - key: nuclei_2d
    display_name: Nuclei (2D)
    command: stardist-napari.data.nuclei_2d
  - key: nuclei_3d
    display_name: Nuclei (3D)
    command: stardist-napari.data.nuclei_3d
  - key: he_2d
    display_name: H&E Nuclei (2D RGB)
    command: stardist-napari.data.he_2d
```

We'll present this information in a "technical specifications" section for each plugin, with links back to the Github line where specific commands are implemented.

For example, StarDist's technical specs section might look like...

**Widgets**
- [StarDist](https://github.com/stardist/stardist-napari/blob/main/stardist_napari/_dock_widget.py#L1704)

**Sample Data**
- [Nuclei (2D)](https://github.com/stardist/stardist-napari/blob/main/stardist_napari/_sample_data.py#L1)
- [Nuclei (3D)](https://github.com/stardist/stardist-napari/blob/main/stardist_napari/_sample_data.py#L7)
- [H&E Nuclei (2D RGB)](https://github.com/stardist/stardist-napari/blob/main/stardist_napari/_sample_data.py#L13)
