### ISSUE TITLE
Manifest endpoint doesn't display well-formatted `yaml`

### ISSUE THREAD

**Issue by DragaDoncila** [chanzuckerberg/napari-hub#570]
#### Description
When visiting the manifest endpoint of a plugin, the metadata is not well formatted into `yaml`, as `flask` does not provide a `yamlify` method equivalent to the `jsonify` method we're using to display the plugin jsons correctly.

While this doesn't affect the underlying data, we should endeavor to improve this. Manifests also support being written out to `json` instead of `yaml`, so this would also be an alternative option.

#### Steps/Code to Reproduce
Visit the [manifest endpoint](https://api.staging.napari-hub.org/manifest/hesperos) for hesperos and note that the output is just formatted as raw text.

#### Expected Results
The results are nicely formatted as yaml e.g.

```
name: hesperos
display_name: Hesperos application
contributions:
  commands:
    - id: hesperos.make_manual_segmentation_widget
      python_name: hesperos._manual_widget:ManualSegmentationWidget
      title: Make Manual Segmentation Widget
    - id: hesperos.make_oneshot_segmentation_widget
      python_name: hesperos._oneshot_widget:OneShotWidget
      title: Make OneShot Segmentation Widget

  widgets:
    - command: hesperos.make_manual_segmentation_widget
      display_name: Manual Segmentation or Correction
    - command: hesperos.make_oneshot_segmentation_widget
      display_name: OneShot Segmentation 
```

#### Actual Results

```
contributions: commands: - id: hesperos.make_manual_segmentation_widget python_name: hesperos._manual_widget:ManualSegmentationWidget title: Make Manual Segmentation Widget - id: hesperos.make_oneshot_segmentation_widget python_name: hesperos._oneshot_widget:OneShotWidget title: Make OneShot Segmentation Widget widgets: - command: hesperos.make_manual_segmentation_widget display_name: Manual Segmentation or Correction - command: hesperos.make_oneshot_segmentation_widget display_name: OneShot Segmentation display_name: Hesperos application name: hesperos schema_version: 0.1.0
```
