### ISSUE TITLE
Open PRs to plugins using preview page action with minor revision version specified

### ISSUE THREAD

**Issue by DragaDoncila** [chanzuckerberg/napari-hub#640]
### Summary
When we initially wrote the guide for setting up the preview page, we specified a full version in the GitHub actions yaml snippet e.g.

```yaml
  - name: napari hub Preview Page Builder
    uses: chanzuckerberg/napari-hub-preview-action@v0.1.4 # specified to minor revision
    with:
      hub-ref: main
```
This means minor updates to the preview page action will not be reflected in user's repositories without them manually updating their GitHub action. 

We should open PRs to these repositories to change their preview page action to exclude the minor revision version, so that users can have the latest preview page experience.

### Intended Outcome

Preview page users will get the latest changes to the preview page without updating their action each time.

### How will it work?

We will need to determine which plugin repositories are using the preview page - I don't know whether there's a way to find references to a GitHub action without "scraping" the GitHub information for each repository.

Once that's determined opening the Pull Requests should be trivial. We should either update to show only the major version e.g. `uses: chanzuckerberg/napari-hub-preview-action@v0` or one level deeper e.g. `uses: chanzuckerberg/napari-hub-preview-action@v0.1`

We should also update our documentation to reflect this change.

cc @neuromusic
